# Generated by Django 5.0.6 on 2024-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_rename_reseña_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
