# Generated by Django 5.0.6 on 2024-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_remove_autor_fecha_nacimiento_libro_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
