# Generated by Django 5.0.6 on 2024-07-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_cliente_avatar_alter_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
