# Generated by Django 5.0.6 on 2024-07-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_cliente_tipo_cliente_alter_cliente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='fecha',
            new_name='fecha_orden',
        ),
        migrations.CreateModel(
            name='ClienteOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=300)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_online',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.clienteonline'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cliente_tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreria.clientetienda'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.clientetienda')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.libro')),
            ],
        ),
        migrations.AddField(
            model_name='clientetienda',
            name='libros_comprados',
            field=models.ManyToManyField(through='libreria.Compra', to='libreria.libro'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
