# Generated by Django 5.0.6 on 2024-07-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0022_remove_libro_imagen_url_libro_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars\\default-avatar.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
