# Generated by Django 5.0.6 on 2024-07-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0023_alter_perfil_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='\\media\\libros'),
        ),
    ]
